### ISSUE TITLE
knife openstack server create fails on Windows2012r2 on WinRM connection ,,, Knife-openstack/ knif-cloud

### ISSUE THREAD

**Issue by thindiyeh** [chef/knife-cloud#100]
This issue described on knife-openstack issues, but its related to knife-cloud

https://github.com/chef/knife-openstack/issues/186

Please review and let me know if you have a fix for it

**Comment by jjasghar** [comment]
Unfortunatly, I run them both. How do you know it's related to `knife-cloud`? I'd love to learn how you tracked that down.

**Comment by jjasghar** [comment]
@thindiyeh (i think we talked to each other today!) https://github.com/chef/knife-cloud/blob/master/CHANGELOG.md#v121-2016-02-24 has been released which should resolve this issue. Please reopen if it's not fixed.

**Comment by jjasghar** [comment]
I should say also that you need to update `knife-cloud` via however you update your gems.
