### ISSUE TITLE
Setting `node-ssl-verify-mode none` does not work

### ISSUE THREAD

**Issue by russellseymour** [chef/knife-cloud#107]
# Version: 

1.2.1

# Environment: 

Writing a new knife plugin based on knife cloud. 

# Scenario:

I am successfully cloning the new machine and getting the IP address to bootstrap the machine. The bootstrap works successfully but it is not passing the `--node-ssl-verify-mode none` option to chef-client so it fails when trying to register with the chef server.

# Steps to Reproduce:

As far as I can tell this should happen on any system that uses knife cloud with self signed certificates on the Chef server.

# Expected Result:

The `/etc/chef/client.rb` file should contain `ssl_verify_mode :verify_none`.

# Actual Result:

All of the settings for the `/etc/chef/client.rb` are set, e.g. the Chef Server URL, validator name and the key itself are all correct. However it is missing the `ssl_verify_mode` setting in the file.

**Comment by kapilchouhan99** [comment]
Hi @russellseymour, Latest `knife-cloud` is now dependent on `chef 15` and `--node-ssl-verify-mode` option is moved from `knife-cloud` to `chef 15`, so please use the latest `knife-cloud` and `chef` versions.

Please let me know if you are facing any issue.
Thank you.
