### ISSUE TITLE
both -F json ad --format json does not work 

### ISSUE THREAD

**Issue by jjasghar** [chef/knife-cloud#91]
To quote a user:

@b-slim: I want to get the summary of the kinfe openstack create as json object, thought using -F json or --format json will do so, but i do get the same output (without fromating)

**Comment by b-slim** [comment]
Thanks @jjasghar, just to clarify my use case:
i want to be able to get the result of the create command in a json object that i can parse and extract instance id using json parser. Thanks!

**Comment by adamedx** [comment]
So I'd really like to understand the scope of the issue. The `--format` option is part of `knife` itself. What issue are we actually encountering here:

* The option only works for some knife plugins?
* The option is broken for knife-openstack only?
* If it's broken for other plugins, what are they? Does this include knife-windows?

I'd like to be sure that in addressing this problem it's addressed in the right place, preferably not with multiple fixes.

**Comment by NimishaS** [comment]
@adamedx, `--format` options doesn't work for any knife-plugin. It works for only `knife`.

**Comment by jjasghar** [comment]
@b-slim I have pushed out a pre-release of the `knife-openstack` gem that supports this now. Please test it out and can you see if it answers your feature request?

`gem install knife-openstack --pre`

Thanks!

**Comment by b-slim** [comment]
@jjasghar Thanks ! i did install it 
but when i run `knife openstack server list --format json -c conf_openstack` i do get the summary result and not a json object.
This is what i am using as gems
```ruby
Fetching: knife-cloud-1.1.0.gem (100%)
Successfully installed knife-cloud-1.1.0
Fetching: knife-openstack-1.3.0.rc.0.gem (100%)
Successfully installed knife-openstack-1.3.0.rc.0
2 gems installed
 ```

**Comment by jjasghar** [comment]
Ah, you need to do the --pre with knife-cloud also. 

Please update that also and try again. 

- JJ Asghar

**Comment by b-slim** [comment]
@jjasghar Cool it works !! thanks guys ! :+1:

**Comment by jjasghar** [comment]
Awesome, i'll close this per this PR https://github.com/chef/knife-openstack/pull/168
