### ISSUE TITLE
Other knife plugins using knife-cloud underneath it.

### ISSUE THREAD

**Issue by patcon** [chef/knife-cloud#99]
Might be something to pursue if the digitalocean plugin starts using this library, as they have a rebuild endpoint that is very useful during testing when you want to revert back to the original image, but keep your IP.

**Comment by jjasghar** [comment]
There are a couple DO `knife` plugins, which one do you think would use `knife-cloud` under the sheets?

**Comment by patcon** [comment]
Really? I actually only found one: https://github.com/rmoriz/knife-digital_ocean

It seems to be kept up-to-date, so I thought the maintainer might be amenable. Really curious to hear about other options if you could share :)

**Comment by jjasghar** [comment]
Wow, i guess i was wrong. I swear there was a `knife-digitialocean` at some point. Yeah @rmoriz 's plugin is the one i normally use myself.

**Comment by patcon** [comment]
:)

Actually, could probably just document how to create a rebuild command by generalizing delete, right? But anyhow, first thing is to get the plugin using this repo...!

**Comment by jjasghar** [comment]
:metal: totally. Maybe we can get @rmoriz to chime in here and we can see if he's up to it.

**Comment by jjasghar** [comment]
Went ahead and posted on `knife-rackspace` to see if they could start looking at refactoring for `knife-cloud` also: https://github.com/chef/knife-rackspace/issues/124

**Comment by patcon** [comment]
And there's also an issue for that in knife-digital_ocean too, so perhaps any related convo could be there, and this could be more on-topic :)

https://github.com/rmoriz/knife-digital_ocean/issues/82
